---
title: "Group project algo"
author: "ML"
date: "12/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tm")
library("tidytext")
library("proustr")
library("tidyverse")
devtools::install_github("ThinkRstat/stopwords", force = TRUE)
library("stopwords")
```


```{r}
annonces <- read.csv("descri.csv")
annoncesmini<- tolower(annonces$Description)
unwanted_array = list(     'Ž'='Z', 'ž'='z', 'À'='A', 'Á'='A', 'Â'='A', 'Ã'='A', 'Ä'='A', 'Å'='A', 'Æ'='A', 'Ç'='C', 'È'='E', 'É'='E',
                            'Ê'='E', 'Ë'='E', 'Ì'='I', 'Í'='I', 'Î'='I', 'Ï'='I', 'Ñ'='N', 'Ò'='O', 'Ó'='O', 'Ô'='O', 'Õ'='O', 'Ö'='O', 'Ø'='O', 'Ù'='U',
                            'Ú'='U', 'Û'='U', 'Ü'='U', 'Ý'='Y', 'Þ'='B', 'ß'='Ss','á'='a',"à"="a", 'â'='a', 'ã'='a', 'ä'='a', 'å'='a', 'æ'='a', 'ç'='c', 
                         'è'='e', 'é'='e', 'ê'='e', 'ë'='e', 'ì'='i', 'í'='i', 'î'='i', 'ï'='i', 'ð'='o', 'ñ'='n', 'ò'='o', 'ó'='o', 'ô'='o', 'õ'='o',
                            'ö'='o', 'ø'='o', 'ù'='u', 'ú'='u', 'û'='u', 'ý'='y', 'ý'='y', 'þ'='b', 'ÿ'='y' )
cleanannonces <- chartr(paste(names(unwanted_array), collapse=''),
         paste(unwanted_array, collapse=''),
         annoncesmini) %>% removePunctuation()

```

```{r}

roadnames <- read.csv("roadnames.csv")
roadnames <- roadnames[-c(35,4822, 12874, 13057, 17218, 20551, 20597,21831, 23291, 30137, 30640, 30641, 30642, 32100, 33021, 33384, 33842, 34725, 34767, 34913, 34957, 37145, 37525, 37769, 38212,38289, 38721, 38804, 38813, 32689:32698, 26923, 26924, 32616:32618, 17093, 37459, 30167, 32011:32036, 33720, 26108, 18807, 25850, 32614, 36639, 29994, 33291, 38029, 38090, 35951, 38316), ]
roadmini<- tolower(roadnames$name)

cleanroad <- chartr(paste(names(unwanted_array), collapse=''),
         paste(unwanted_array, collapse=''),
         roadmini)
cleanroadf <- data.frame(cleanroad)

stationames <- read.csv("nom_stations.csv")
stationames <- stationames[-c(30), ]
stationmini <- tolower(stationames)
cleanstation <- chartr(paste(names(unwanted_array), collapse=''),
         paste(unwanted_array, collapse=''),
         stationmini)




```

```{r}
x <- sapply(cleanroad, function(x) grepl(x, cleanannonces ,ignore.case = F ,perl = F,
      fixed = TRUE, useBytes = FALSE))
extrait <- apply(x, 1, function(i) paste0(names(i)[i], collapse = ","))
ruedescription<- data.frame(extrait)


num_rue <- str_extract(cleanannonces, "(?!=rue\\s)\\d+\\d+")
ID <- c(1:140)
numberuec <-data.frame(ID,num_rue)
numero_de_rue=apply(numberuec,2,as.numeric)
numero_de_rue[numero_de_rue>500]=NA
numero_de_rue <- data.frame(numero_de_rue)
numero_rue <- numero_de_rue$numberue
numero_rue <- data.frame(numero_rue)


station <- sapply(cleanstation, function(x) grepl(x, cleanannonces ,ignore.case = F ,perl = F,
      fixed = TRUE, useBytes = FALSE))
stationextrait <- apply(station, 1, function(i) paste0(names(i)[i], collapse = ","))
station_nom <- data.frame(stationextrait)


fullextrait <- data.frame( numero_de_rue, ruedescription,  station_nom)
fullextrait

```






